### ISSUE TITLE
Support converter as companion object

### ISSUE THREAD

**Issue by jhult** [TouK/krush#33]
It would be nice to be able to have a converter as an object. Example:

```
data class JobId(val id: Long = 0) {

    override fun toString(): String = id.toString()

    companion object : AttributeConverter<JobId, Long>() {
        override fun convertToDatabaseColumn(attribute: JobId): Long = attribute.toLong()
        override fun convertToEntityAttribute(dbData: Long): JobId = JobId(attribute)
    }
}
```
And using that converter:
```
@Entity
data class Resource(
    @Id val id: Long = 0,

    @Convert(converter = JobId.Companion::class)
    @Json(name = "job_id")
    val jobId: JobId = JobId()
)

```

Right now, the following throws errors in the generated `tables.kt`:
```
fun Table.job_id(columnName: String): Column<JobId> = longWrapper<JobId>(columnName, {
    com.mypackage.ids.JobId.Companion().convertToEntityAttribute(it) }, {
    com.mypackage.ids.JobId.Companion().convertToDatabaseColumn(it) })
}
```
This is because of the `()` after `JobId.Companion`. If the `()` are removed, then I believe it would work fine for objects (but obviously cause issues for classes).

I think the code where this occurs is located here: https://github.com/TouK/krush/blob/master/annotation-processor/src/main/kotlin/pl/touk/krush/source/TablesGenerator.kt#L221

A sneaky workaround is to add this function to the object:
```
fun Companion(): Companion = Companion
```

**Comment by pjagielski** [comment]
Hi, thanks for the issue. Generally companions are not supported currently... I think we might rewrite this by using more info about `Converter` from `kotlipoet-metadata`
