### ISSUE TITLE
Bump to Exposed 0.23.x

### ISSUE THREAD

**Issue by pjagielski** [TouK/krush#4]
* primaryKey depracated, migrate to `override val primaryKey`
* new package org.jetbrains.exposed.sql.`java-time`

**Comment by NickAcPT** [comment]
Has there been any progress on this?

**Comment by pjagielski** [comment]
Hi, we had a little freeze after last release, but it's time to move on, this issue is highest priority!

**Comment by pjagielski** [comment]
Merged, to be released in 0.3.0
