### ISSUE TITLE
My god, this orm is great, but there is no documentation for the Chinese version

### ISSUE THREAD

**Issue by UIdoer** [TouK/krush#5]
My god, this orm is great, but there is no documentation for the Chinese version

**Comment by pjagielski** [comment]
You mean some kind of Chinese tutorial for Krush?

**Comment by UIdoer** [comment]
Yes, I think there are a large number of people who need Chinese tutorial. The Chinese market has been occupied by mybatis, which is a sad thing for me who is not good at English. If I can, I think I will see krush Chinese tutorial in my lifetime😂------------------ 原始邮件 ------------------
发件人: "Piotr Jagielski"<notifications@github.com>
发送时间: 2020年1月15日(星期三) 凌晨1:07
收件人: "TouK/krush"<krush@noreply.github.com>;
抄送: "UIdoer"<xian-zi-ming@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [TouK/krush] My god, this orm is great, but there is nodocumentation for the Chinese version (#5)



You mean some kind of Chinese tutorial for Krush?
 
&mdash;

**Comment by pjagielski** [comment]
You can check Ktorm is has tutorial in Chinese https://github.com/vincentlauvlwj/Ktorm/blob/master/README_cn.md and it's really similar to Exposed
