### ISSUE TITLE
Support for batch insert

### ISSUE THREAD

**Issue by Namnodorel** [TouK/krush#57]
Exposed has `EntityTable.batchInsert()` for inserting multiple items at once. Having something similar generated by krush would be more efficient than calling  `EntityTable.insert(entity)` for every item individually.

**Comment by pjagielski** [comment]
Hi, I added `batchInsert` example to krush-example project: https://github.com/TouK/krush-example/blob/master/src/test/kotlin/pl/touk/krush/ReservationTest.kt#L120

I think no additional change in krush is needed ;)

**Comment by Namnodorel** [comment]
That indeed solves the issue nicely. Thank you!
