### ISSUE TITLE
breaking tests due to old exposed version

### ISSUE THREAD

**Issue by ChristianSch** [TouK/krush#60]
HI!

the root cause of our failing tests (https://github.com/TouK/krush/issues/54) apparently hasn't been fixed in exposed v0.32.1 but needs 0.33.1, which is also quite old and newer versions need major changes apparently. that's why I made a PR (https://github.com/TouK/krush/pull/59) a while ago to have dependabot make PRs for available updates to keep up. it's quite important to be up to date in the database layer because of vulnerabilities of dependencies.

right now we help ourselves with the following hack in our gradle config, which is quite ugly and also deprecated:
```
    // forces exposed to be > 0.33.1, fixing failing tests. this is a transitive dependency of krush
    // we can remove this extra config after krush updates exposed
    api("org.jetbrains.exposed:exposed-jdbc:$exposedVersion") {
        isForce = true
    }
    api("org.jetbrains.exposed:exposed-core:$exposedVersion") {
        isForce = true
    }
    api("org.jetbrains.exposed:exposed-java-time:$exposedVersion") {
        isForce = true
    }
```

**Comment by pjagielski** [comment]
Fixed in 0.6.0
